#!/bin/bash

# Instructions of pre-defined commands

function print_ALIAS_HOWTO_ {
    cat << EOF
    -----------------------------------------
    CATAPULT VASP job submission script HOWTO
    -----------------------------------------
    Use 'source ~/.bashrc' to activate pre-defined
    commands

    Pre-defined commands
        Pvasp6     : Run parallel standard VASP calculations
        Pvasp6_g   : Run parallel Gamma-only VASP calculations
        Pvasp6_nc  : Run parallel non-collinear VASP calculations
        Xvasp6     : Run user defined commands (Advanced)
        Gvasp6     : Run parallel standard VASP calculations on GPU
        Gvasp6_g   : Run parallel Gamma-only VASP calculations on GPU
        Gvasp6_nc  : Run parallel non-collinear VASP calculations on GPU
        XGvasp6     : Run user defined commands on GPU (Advanced)
        SETvasp6   : Quick reference of settings file
        HELPvasp6  : Print help file

    Example code:
        Pvasp6 -in mgo.in -wt 02:00 -nd 2
        Xvasp6 -name mag-band -nd 1 -x std -in mgo.in -wt 01:00 -ref no -x std -in band.in -wt 00:30 -ref mgo

EOF
}

# Instructions of user-defined commands

function print_GENSUB_HOWTO_ {
    SOURCE=$CTRLDIR/gen_sub
    source $SOURCE -help
}

print_ALIAS_HOWTO_

if [[ $1 == 'gensub' ]]; then
    CONFIGDIR=$(realpath $(dirname $0))
    CTRLDIR=$(realpath "$CONFIGDIR"/../)
    print_GENSUB_HOWTO_
fi
